version: '3.7'

services:
    spark-master:
        image: docker.io/bitnami/spark:3.5
        container_name: spark-master
        environment:
            - SPARK_MODE=master
            - SPARK_MASTER_WEBUI_PORT=8080
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
            - SPARK_USER=spark
        ports:
            - "9090:8080"
    spark-worker:
        image: docker.io/bitnami/spark:3.5
        depends_on:
            - spark-master
        environment:
            - SPARK_MODE=worker
            - SPARK_WORKER_WEBUI_PORT=8081
            - SPARK_MASTER_URL=spark://spark-master:7077 
            - SPARK_WORKER_MEMORY=512m
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
            - SPARK_USER=spark
