version: '3.7'

networks:
  spark-network:

services:
    spark-master:
        image: docker.io/bitnami/spark:3.5
        container_name: spark-master
        env_file:
            - ".env"
        environment:
            - SPARK_MODE=master
            - SPARK_MASTER_WEBUI_PORT=${SPARK_MASTER_WEBUI_PORT}
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
            - SPARK_USER=spark
        ports:
            - "${SPARK_MASTER_WEBUI_EXPOSED_PORT}:${SPARK_MASTER_WEBUI_PORT}"
        networks:
            - spark-network
        volumes:
            - spark-datafiles:/opt/bitnami/spark/data/datafiles
            # - ${LOCAL_PATH_TO_APP}:/opt/bitnami/spark/app

    spark-worker:
        image: docker.io/bitnami/spark:3.5
        depends_on:
            - spark-master
        env_file:
            - ".env"
        environment:
            - SPARK_MODE=worker
            - SPARK_WORKER_WEBUI_PORT=${SPARK_WORKER_WEBUI_PORT}
            - SPARK_MASTER_URL=spark://spark-master:7077 
            - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
            - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
            - SPARK_USER=spark
        networks:
            - spark-network
        scale: ${NUM_OF_WORKERS}
        volumes:
            - spark-datafiles:/opt/bitnami/spark/data/datafiles

    # sbt:
    #     image: hseeberger/scala-sbt:8u252_1.3.10_2.13.2
    #     container_name: sbt-container
    #     working_dir: /opt/bitnami/spark/app  # Set the working directory to your Spark app
    #     volumes:
    #         - ${LOCAL_PATH_TO_APP}:/opt/bitnami/spark/app
    #     command: sbt run


volumes:
  spark-datafiles:
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_PATH_TO_DATASET}
      o: bind

